import type { SafeTableProjection } from "@friend-poker/shared";

export function projectionFixture(overrides: Partial<SafeTableProjection> = {}): SafeTableProjection {
  return {
    version: 7,
    status: "HAND_IN_PROGRESS",
    hostPlayerId: "alice",
    seats: [
      {
        playerId: "alice",
        nickname: "Alice",
        seat: 0,
        present: true,
        online: true,
        pendingLeaveAfterHand: false,
        chipBalance: 94,
      },
      null,
      {
        playerId: "bob",
        nickname: "Bob",
        seat: 2,
        present: true,
        online: false,
        pendingLeaveAfterHand: false,
        chipBalance: 72,
      },
      null,
      null,
      null,
    ],
    spectators: [
      {
        playerId: "watcher",
        nickname: "Watcher",
        seat: null,
        present: true,
        online: true,
        pendingLeaveAfterHand: false,
        chipBalance: 100,
      },
    ],
    session: {
      sessionId: "session-1",
      blinds: { smallBlind: 1, bigBlind: 2 },
      completedHandCount: 3,
      lastButtonSeat: 0,
      ledger: [],
    },
    currentHand: {
      handId: "hand-1",
      status: "BETTING",
      participants: [
        {
          playerId: "alice",
          seat: 0,
          startingStack: 100,
          stack: 94,
          streetContribution: 2,
          totalContribution: 6,
          folded: false,
          allIn: false,
        },
        {
          playerId: "bob",
          seat: 2,
          startingStack: 100,
          stack: 72,
          streetContribution: 6,
          totalContribution: 28,
          folded: false,
          allIn: false,
        },
      ],
      buttonSeat: 0,
      smallBlindSeat: 0,
      bigBlindSeat: 2,
      smallBlind: 1,
      bigBlind: 2,
      street: "FLOP",
      currentActorId: "alice",
      currentBet: 6,
      potSize: 34,
      board: [
        { rank: 14, suit: "s" },
        { rank: 13, suit: "h" },
        { rank: 2, suit: "c" },
      ],
      actions: [],
    },
    viewerLegalActions: null,
    viewerCanRevealUncontested: false,
    ownHoleCards: [
      { rank: 14, suit: "h" },
      { rank: 14, suit: "d" },
    ],
    recentHands: [],
    recentSessions: [],
    ...overrides,
  };
}
